spring:
  datasource:
    platform: h2
    jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true